name: Generate Data and OG Images

on:
    pull_request:
        branches: [main]

jobs:
    generate-and-commit:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Generate Data
              run: pnpm generate:data
              env:
                  NODE_VERSION: '22'

            - name: Generate OG Images
              run: pnpm generate:og
              env:
                  NODE_VERSION: '22'

            - name: Commit and Push changes
              id: auto-commit
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_options: '--no-verify'
                  commit_message: 'chore: auto-generate data and og images'

            - name: Comment on PR
              if: steps.auto-commit.outputs.changes_detected == 'true'
              uses: thollander/actions-comment-pull-request@v3
              with:
                  message: |
                      ### Data Generation Update
                      New data and OG images have been automatically generated. 
                      Please **review the changes** and ensure that any missing **descriptions** or **colors** are filled in manually.
                  github-token: ${{ secrets.GITHUB_TOKEN }}
